### model
model_name_or_path: google/paligemma2-10b-pt-448
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 64
lora_alpha: 64
lora_dropout: 0.05
lora_target: all
# freeze_multi_modal_projector: false
# freeze_vision_tower: false

### dataset
dataset: banglaprotha
template: paligemma
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/paligemma2-finetune/lora/sft
logging_steps: 1
save_steps: 2400000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 2.0e-4
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
run_name: Paligemma-lora-finetune-banglaprotha


# wandb
# report_to: wandb
# run_name: llava-lora-finetune-banglaprotha

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
