### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 64
lora_alpha: 64
lora_dropout: 0.05
lora_target: all
# freeze_multi_modal_projector: false
# freeze_vision_tower: false
# deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: banglaprotha
template: qwen2_vl
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

# ### loss = 0; grad_norm = NaN fix
# flash_attn: fa2

### output
output_dir: saves/Qwen2.5-7B-Instruct-v2/lora/sft
logging_steps: 1
save_steps: 2400000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8 # a100/ change to 4 for a40
gradient_accumulation_steps: 4
learning_rate: 2.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
run_name: qwen-lora-finetune-banglaprotha
### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
